name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
     name:
      description: 'Who initiating this workflow?'
      required: true
     reason:
      description: 'Reason for initiation?'
      required: true


jobs:

  BUILD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
           node-version: ${{matrix.node-version}}

      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build
        
      - name: Run the tests and generate coverage
        run: npm test -- --coverage
        
  TEST:
    runs-on: ubuntu-latest
    needs: BUILD
    
    steps:
       - name: Test coverage
         run: echo Test coverage reported in BUILD job
         
  DEPLOYMENT:
    runs-on: ubuntu-latest
    needs: [BUILD, TEST]
    
    steps:
      
      - name: Deploy Application
        run: |
         echo Your deployment script goes here
