name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
     name:
      description: 'Who initiating this workflow?'
      required: true
     reason:
      description: 'Reason for initiation?'
      required: true


jobs:

  BUILD:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build
        
  TEST:
    runs-on: ubuntu-latest
    needs: BUILD
    
    steps:
       - name: Run the tests
         run: npm test
         
  DEPLOYMENT:
    runs-on: ubuntu-latest
    needs: [BUILD, TEST]
    
    steps:
      
      - name: Deploy Application
        run: |
         echo Your deployment script goes here